//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;http://sdshare.com/unittesting/order/1&gt; &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#type&gt; &lt;http://sdshare.com/unittesting/Order&gt; .
        ///&lt;http://sdshare.com/unittesting/order/1&gt; &lt;http://sdshare.com/unittesting/order/description&gt; &quot;Testing&quot; ..
        /// </summary>
        internal static string Triples {
            get {
                return ResourceManager.GetString("Triples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------WebKitFormBoundarysoh7g9XuBMxTzC9M
        ///Content-Disposition: form-data; name=&quot;value&quot;; filename=&quot;triples.txt&quot;
        ///Content-Type: text/plain
        ///
        ///&lt;http://sdshare.com/unittesting/order/1&gt; &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#type&gt; &lt;http://sdshare.com/unittesting/Order&gt; .
        ///&lt;http://sdshare.com/unittesting/order/1&gt; &lt;http://sdshare.com/unittesting/order/ordernumber&gt; 1 .
        ///&lt;http://sdshare.com/unittesting/order/1&gt; &lt;http://sdshare.com/unittesting/order/description&gt; &quot;Testing&quot; .
        ///------WebKitFormBoundarysoh7g9XuBMxTz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebKitPayload {
            get {
                return ResourceManager.GetString("WebKitPayload", resourceCulture);
            }
        }
    }
}
